Bump to version 1.2.3
conda-forge/scipy-feedstock pull request #134
Opened 2020-09-12 12:57 UTC by johanjeppsson

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~~[ ] Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

2020-09-12 12:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-09-12 13:20 UTC, beckermr requested changes
CI did not run

2020-09-12 13:20 UTC, beckermr commented
@conda-forge-admin restart ci

2020-09-12 16:33 UTC, beckermr commented
@conda-forge-admin please restart ci

2020-09-12 16:44 UTC, beckermr commented on recipe/meta.yaml
>    skip: true  # [win or aarch64 or ppc64le or py3k]
```suggestion
  skip: true  # [win or aarch64 or ppc64le]
```

2020-09-12 16:44 UTC, beckermr commented
@conda-forge-admin rerender

2021-07-19 08:43 UTC, mattip commented
Outdated, can be closed

2021-07-19 08:47 UTC, closed without merging